import fonts from "./components/fonts/fonts"

import "./scss/style.scss";

import searchForm from "./components/search-form/search-form"
import cards from "./components/cards/cards"
import regForm from "./components/reg-form/reg-form"
import buttons from "./components/buttons/buttons"
import signIn from "./components/sign-in/sign-in"
import calendar from "./components/calendar/calendar"
import booking from "./components/booking/booking"
import searchItem from "./components/search-item/search-item"
import header from "./components/header/header"
import footer from "./components/footer/footer"
import logo from "./components/logo/logo"
import promo from "./components/promo/promo"
import filter from "./components/room-filter/filter"
import searchPage from "./components/search-page/search-page"
import roomDetails from "./components/room-details/room-details"
import colorsAndTypes from "./components/colors-and-types/colors-and-types"